### ISSUE TITLE
Require function for stack policy inclusion and override.

### ISSUE THREAD

**Issue by sobil** [seek-oss/evaporate#17]
When upserting cfn the ability to insert a stack policy would be benificial.

This would also require an ability to override with the inclusion of a specified temporary policy and even a built in god mode *:* built in policy.

**Comment by askoufis** [comment]
What do you mean by a god mode stack policy? By default, if no stack policy is specified then any resource can have any action made upon it by changes in the the template.

**Comment by sobil** [comment]
yes i believe that is true, but does evaporate require a policy or can it be left optional

**Comment by askoufis** [comment]
Stack policies are written inside your stack template - evaporate does not interact with them in anyway.
