### ISSUE TITLE
AWS_REGION is ignored by credentials discovery when it falls back to EC2 instance metadata

### ISSUE THREAD

**Issue by screamish** [seek-oss/evaporate#20]
See https://hackage.haskell.org/package/amazonka-1.4.5/docs/Network-AWS.html#v:Discover for details.

I think we need to look for AWS_REGION in the env ourselves if we want to be able to override the region while still getting credentials via the EC2 instance metadata

**Comment by daniel-chambers** [comment]
I feel like specifying that standard region env var with the expectation that it overrides the instance metadata goes against how standard AWS SDK authentication works. I reckon we might be better off exposing a command line argument or a differently named env var if we want to override the standard mechanism for determining credentials & region.

**Comment by askoufis** [comment]
So maybe something like a CLI arg that applies to all stacks initially, but is then overwritten by an explicit declaration of the region in the stack description, if present.

**Comment by screamish** [comment]
That sounds like a good approach.
