### ISSUE TITLE
Parameters should be optional

### ISSUE THREAD

**Issue by askoufis-seek** [seek-oss/evaporate#7]
Currently an `evaporate.yaml` file like this:

```
a-stack-name:
  template-path: template.json
  parameters: {}

```

Fails like this:

```
$ evaporate get
evaporate: AesonException "Error in $.parameters: failed to parse field parameters: expected HashMap Text a, encountered Null"
```

It should be easy enough to create a special case whereby if no parameters have been specified at all, bypass the account parameters lookup part.

**Comment by screamish** [comment]
Implemented by #18
